CREATE TABLE USERS(
    ID NUMBER(5) PRIMARY KEY,
    USERNAME VARCHAR2(30),
    PASSWORD VARCHAR2(100),
    EMAIL VARCHAR2(30)
);


SELECT * FROM USERS;
SELECT * FROM POST;

DELETE FROM POST WHERE ID=6;
COMMIT;